import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import { Toaster } from "sonner";
import { Providers } from "./Providers";
import AuthInitializer from "@/components/Authcomponent/AuthInitializer";
import SessionHandler from "@/components/Authcomponent/SessionHandler";
import ClientChat from "@/components/Chat/ClientChat/ClientChat";
// import { getServerSession } from "next-auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Power Training | Web App for Gym Training",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await getServerSession();
  return (
    <html lang="en">
      <Providers>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
        >
          <SessionHandler />
          <AuthInitializer />
          <Navbar />
          <main className="flex-grow bg-gray-100">
            <Toaster position="top-center" richColors />
            {children}
            <ClientChat />
          </main>
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
